name: 'Deploy AWS'
description: 'Deploy AWS'
inputs:
  technology:
    description: 'The technology to deploy (e.g. IAC, Serverless, CodeDeploy, etc.)'
    required: true
  aws-function:
    description: 'The AWS function to deploy (e.g. "EC2", "Lambda", "S3", Terraform, CloudFormation, etc.)'
    required: true
  terraform-cmd:
    required: false
    default: 'plan'
    description: 'The Terraform command to run (e.g. "plan", "apply", "destroy", etc.)'
  terraform-args:
    required: false
    default: '-var-file=terraform.tfvars'
    description: 'The Terraform arguments to pass to the command (e.g. "-var-file=terraform.tfvars")'
  
outputs:
  aws-function:
    description: 'The AWS function to deploy'
runs:
  using: 'node16'
  main: 'dist/index.js'