name: 'Deploy AWS'
description: 'Deploy AWS'
inputs:
  technology:
    description: 'The technology to deploy (e.g. IAC, Serverless, CodeDeploy, etc.)'
    required: true
  aws-function:
    description: 'The AWS function to deploy (e.g. "EC2", "Lambda", "S3", Terraform, CloudFormation, etc.)'
    required: true
  
outputs:
  aws-function:
    description: 'The AWS function to deploy'
runs:
  using: 'node16'
  main: 'dist/index.js'