on:
  push:
    branches:
      - main

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: .github/actions/deploy-aws
      - name: Deploy AWS
        uses: ./.github/actions/deploy-aws
        with:
          technology: 'IAC'
          aws-function: 'Cloudformation'