on:
  push:
    branches:
      - main

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: .github/actions/deploy-aws
      - name: Deploy AWS
        uses: ./.github/actions/deploy-aws
        with:
          technology: 'IAC'
          aws-function: 'Terraform'
          terraform-cmd: 'init'
          terraform-args: ''
