on:
  push:
    branches:
      - main

jobs:
  deploy-aws-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: .github/actions/deploy-aws
      - name: Deploy AWS - Terraform
        uses: ./.github/actions/deploy-aws
        with:
          technology: 'IAC'
          aws-function: 'Terraform'
          aws-region: 'us-east-1'
          terraform-cmd: 'init'
          terraform-args: ''
  deploy-aws-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: .github/actions/deploy-aws
      - name: Deploy AWS - CloudFormation
        uses: ./.github/actions/deploy-aws
        with:
          technology: 'IAC'
          aws-function: 'CloudFormation'
          aws-region: 'us-east-1'
          cloudformation-cmd: 'deploy'
          cloudformation-template: '.'